name: ci

on:
  push

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: .git
          check_filenames: true
          check_hidden: true

  lint-docker-compose-file:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: lint zammad docker-compose file
        run: docker-compose config

  super-linter:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-run-docker-compose:
    needs:
      - codespell
      - lint-docker-compose-file
      - super-linter
    timeout-minutes: 20
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build docker containers
        run: .github/docker-image-build.sh

      - name: run docker-compose up
        run: docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.override-local.yml up --detach

      - name: add autowizard file
        run: docker cp .github/auto_wizard.json zammad-docker-compose_zammad-railsserver_1:/opt/zammad

      - name: run tests
        run: .github/tests.sh
        
